### ISSUE TITLE
Typo Line 39 image_enhancement/histogram.py

### ISSUE THREAD

**Issue by vsinha027** [Nguyen-Hoang-Nam/image-enhancement#3]
Seems like there is a small typo on line 39 in image_enhancement/histogram.py
`return self.sub_histogram_equalization(hitogram, range_min, range_max)`

Should be
`return self.sub_histogram_equalization(histogram, range_min, range_max)`

I installed via pip on mac m1.

`Traceback (most recent call last):
  File "--/enhance_images.py", line 22, in <module>
    output = ie.GHE()
  File "/opt/homebrew/lib/python3.9/site-packages/image_enhancement/image_enhancement.py", line 26, in GHE
    LUT = histogram.histogram_equalization(image_1d)
  File "/opt/homebrew/lib/python3.9/site-packages/image_enhancement/histogram.py", line 39, in histogram_equalization
    return self.sub_histogram_equalization(hítogram, range_min, range_max)
NameError: name 'hítogram' is not defined`

the full file path for File is omitted for privacy.

**Comment by Nguyen-Hoang-Nam** [comment]
Thank you, I will check it soon as I come home.

**Comment by Nguyen-Hoang-Nam** [comment]
I just publish version 0.2.1 in [Pypi](https://pypi.org/project/image-enhancement/) which fixes this issue.
